#
# Quit + Advanced Power Management library specific stuff
#

COMPILE_OBJ=quit.obj apm.obj apmif.obj
LIB_NAME=quit.lib
LIST_FILE=quit.lst
LIB_OBJ=-+quit.obj -+apm.obj -+apmif.obj

#
# Generic library stuff
#

INCPATH=..\include;.

CPP_OPTIONS=-O2 -ml -3 -c -d -j6 -I$(INCPATH)
C_OPTIONS=-O2 -mc -3 -c -d -j6 -zCFARCODE -I$(INCPATH)
ASM_OPTIONS=/mx /m3
LIB_OPTIONS=

!ifdef DOS_DEBUG
CPP_OPTIONS=$(CPP_OPTIONS) -DDOS_DEBUG
C_OPTIONS=$(C_OPTIONS) -DDOS_DEBUG
!endif


CPP=$(MAKEDIR)\bcc $(CPP_OPTIONS)
C=$(MAKEDIR)\bcc $(C_OPTIONS)
ASM=$(MAKEDIR)\tasm $(ASM_OPTIONS)
LIB=$(MAKEDIR)\tlib

$(LIB_NAME): $(COMPILE_OBJ)
   $(LIB) @&&!
         $(LIB_NAME) $(LIB_OPTIONS) $(LIB_OBJ), $(LIST_FILE)
!

clean:
   @del *.obj
   @del *.bak
   @del *.lib
   @del *.lst

.cpp.obj:
   $(CPP) $<

.c.obj:
   $(C) $<

.asm.obj:
   $(ASM) $<

