#
# XOSL library specific stuff
#

COMPILE_OBJ=xoslmain.obj xoslapp.obj loader.obj setup.obj bootkeys.obj \
            prefer.obj general.obj password.obj \
            about.obj dialogs.obj xosldata.obj items.obj lastconf.obj \
            encpwd.obj fatfix.obj drvswap.obj part.obj hide.obj \
            graphset.obj colorset.obj mouseset.obj xoslpass.obj misc.obj \
            default.obj antivir.obj bypass.obj strtable.obj
LIB_NAME=xosl.lib
LIST_FILE=xosl.lst
LIB_OBJ=-+xoslmain.obj -+xoslapp.obj -+loader.obj -+setup.obj \
        -+bootkeys.obj -+prefer.obj -+general.obj -+password.obj \
        -+about.obj -+dialogs.obj -+xosldata.obj -+items.obj -+lastconf.obj \
        -+encpwd.obj -+fatfix.obj -+drvswap.obj -+part.obj \
        -+hide.obj -+graphset.obj -+colorset.obj -+mouseset.obj \
        -+xoslpass.obj -+misc.obj -+default.obj -+antivir.obj -+bypass.obj \
        -+strtable.obj

#
# Generic library stuff
#

INCPATH=..\include;.

CPP_OPTIONS=-O2 -ml -3 -c -d -j6 -G -Z -I$(INCPATH)
C_OPTIONS=-O2 -mc -3 -c -d -j6 -G -Z -zCFARCODE -I$(INCPATH)
ASM_OPTIONS=/mx /m3
LIB_OPTIONS=

!ifdef DOS_DEBUG
CPP_OPTIONS=$(CPP_OPTIONS) -DDOS_DEBUG
C_OPTIONS=$(C_OPTIONS) -DDOS_DEBUG
!endif


CPP=$(MAKEDIR)\bcc $(CPP_OPTIONS)
C=$(MAKEDIR)\bcc $(C_OPTIONS)
ASM=$(MAKEDIR)\tasm $(ASM_OPTIONS)
LIB=$(MAKEDIR)\tlib

$(LIB_NAME): $(COMPILE_OBJ)
   $(LIB) @&&!
         $(LIB_NAME) $(LIB_OPTIONS) $(LIB_OBJ), $(LIST_FILE)
!

clean:
   @del *.obj
   @del *.bak
   @del *.lib
   @del *.lst

.cpp.obj:
   $(CPP) $<

.c.obj:
   $(C) $<

.asm.obj:
   $(ASM) $<

